services:
  mysql:
    image: mysql:8.0
    container_name: logicinfo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logicinfo
      MYSQL_USER: ael
      MYSQL_PASSWORD: root
      TZ: "America/Sao_Paulo"
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - logicinfo-network

networks:
  logicinfo-network:
    external: true